/**
 * WebSocket wire protocol for the Bravo messenger gateway.
 *
 * IMPORTANT: this file is mirrored by
 * packages/messenger-core/src/transport/protocol.ts — the LIVE client
 * protocol consumed by mobile AND ops-console via @bravo/messenger-core.
 * When you change a shape here, update that mirror in the same commit —
 * type drift between the two files is silent. (AUDIT-2026-08-13 #8: this
 * header used to point at src/modules/messenger/transport/protocol.ts, an
 * ORPHANED stale copy missing 12 wire types — maintainers were being told
 * to mirror into a corpse. That file is now a tombstone re-export.)
 *
 * Framing: every frame is a single JSON object with `event` and optional
 * `data`. This matches the default @nestjs/websockets dispatcher and
 * keeps the client implementation trivial (JSON.stringify / parse).
 */

export interface SessionAddress {
  userId:   string;
  deviceId: number;
}

export interface Ciphertext {
  /** 3 = PreKeyWhisperMessage, 1 = WhisperMessage — see crypto/types.ts */
  type: 1 | 3;
  /** base64-encoded libsignal ciphertext body */
  body: string;
}

// ─── Client → Server ─────────────────────────────────────────────────

export interface ClientPing {
  event: 'ping';
  data?: {ts: number};
}

/**
 * B-100/B-101 — in-place socket re-authentication. The client presents a
 * freshly-refreshed access token so the gateway can swap the socket's
 * claims WITHOUT a disconnect (the P0-6 sweep would otherwise kill a
 * live call the moment the handshake token's jti leaves the allowlist).
 * The server re-runs the full handshake verification and pins identity
 * to the same sub/device — see `handleAuthRefresh`. Client mirror in
 * `@bravo/messenger-core`.
 */
export interface ClientAuthRefresh {
  event: 'auth.refresh';
  data:  {token: string};
}

export interface ClientEnvelopeSend {
  event: 'envelope.send';
  data: {
    to:          SessionAddress;
    /**
     * Sealed Sender v2 outer ECIES wrap (replaces Phase-1
     * `{ciphertext, senderAddressHint}` pair). The relay treats this
     * as opaque bytes — no field on the wire links the envelope back
     * to the sender. The recipient's libsignal SessionCipher and the
     * sender's address both live inside this AES-256-GCM envelope.
     */
    outerSealed: string;
    /** Client-generated correlation id echoed back on `envelope.accepted`. */
    clientMsgId: string;
    /**
     * Disappearing-message deadline (epoch seconds). When set, the relay
     * shrinks this envelope's Redis TTL to match so the sealed ciphertext
     * self-evicts even if the recipient never comes online to ACK.
     */
    expiresAtSec?: number;
    /**
     * Audit P2-BR-3 — false marks a non-displayable envelope (reaction,
     * group-control/rekey, dedup-safe retry) that must NOT fire a
     * chat-wake push. Absent/true (legacy clients) keeps today's wake.
     */
    urgent?: boolean;
  };
}

/**
 * Ack-outcome split (handoff §3.6c) — 'delivered' (default when absent,
 * legacy behavior) emits the sender-facing `envelope.delivered`;
 * 'discarded' (the receiving device destroyed the message on a terminal
 * decrypt failure) deletes the envelope but emits
 * `envelope.undeliverable` instead. See the messenger-core mirror.
 */
export type AckDisposition = 'delivered' | 'discarded';

export interface ClientEnvelopeAck {
  event: 'envelope.ack';
  data: {
    envelopeId: string;
    /**
     * Audit P0-N9 — possession-proof token issued in the deliver
     * frame. Optional during the rollout window; the service rejects
     * missing tokens once `relay.requireAckToken=true`. See the
     * client-side mirror in `@bravo/messenger-core` for full notes.
     */
    ackToken?: string;
    /** See AckDisposition — absent means 'delivered' (legacy). */
    disposition?: AckDisposition;
  };
}

export interface ClientEnvelopePull {
  event: 'envelope.pull';
  data?: {
    after?: string;
    limit?: number;
    /**
     * Restore-after-reinstall fix #4 — bootstrap pulls bypass the
     * normal limit cap. Set to `true` on the FIRST pull after a
     * fresh install so the client gets every pending envelope in
     * one round-trip rather than the default 50/100. The server
     * still enforces an absolute ceiling (`relay.maxBootstrapLimit`,
     * default 1000) to bound memory.
     */
    bootstrap?: boolean;
  };
}

// ─── WebRTC call signalling (M8) ─────────────────────────────────────
//
// The gateway is a PURE RELAY for these frames — it never parses the
// SDP / ICE bodies and never persists them. DTLS-SRTP is verified at
// the callee/caller via `RTCPeerConnection.getStats()` before any
// media track is surfaced to the UI.

export type CallId = string; // UUID generated by the caller

/**
 * Audit S7 — caller-identity binding for `call.offer`. Mirror of the
 * mobile / package-side `CallOfferAuthBlock`. The relay forwards this
 * verbatim from caller → callee and NEVER verifies it — verification
 * happens end-to-end on the callee (`verifyCallOfferAuth` in
 * `@bravo/messenger-core`). Optional on the wire during the rollout
 * window so legacy senders aren't broken; callees fail-closed once
 * telemetry shows zero unsigned offers.
 */
export interface CallOfferAuthBlock {
  cert: string;
  aad: {
    v: number;
    callId: string;
    from: {userId: string; deviceId: number};
    to:   {userId: string; deviceId: number};
    kind: 'voice' | 'video';
    ts:   number;
  };
  sig: string;
}

/**
 * Audit P1-C2 + P1-C3 — answerer-identity / sender-identity binding for
 * `call.answer` and `call.media-state`. Mirror of mobile
 * `CallControlAuthBlock`. Same pass-through semantics as
 * `CallOfferAuthBlock` — gateway never inspects; verified end-to-end.
 */
export interface CallControlAuthBlock {
  cert: string;
  aad: {
    v:        number;
    kind:     'call.answer' | 'call.media-state';
    callId:   string;
    from:     {userId: string; deviceId: number};
    to:       {userId: string; deviceId: number};
    /** Base64 SHA-256 of the canonical body bytes (per-kind shape). */
    bodyHash: string;
    ts:       number;
  };
  sig: string;
}

export interface ClientCallOffer {
  event: 'call.offer';
  data: {
    callId:   CallId;
    to:       SessionAddress;
    /** RTCSessionDescription.sdp as produced by createOffer. */
    sdp:      string;
    /** 'voice' | 'video' — purely informational; recipient UI can pre-switch. */
    kind:     'voice' | 'video';
    /** Audit S7 — caller's signed AAD. Pass-through; gateway does NOT inspect. */
    auth?:    CallOfferAuthBlock;
  };
}

export interface ClientCallAnswer {
  event: 'call.answer';
  data: {
    callId:   CallId;
    to:       SessionAddress;
    sdp:      string;
    /** Audit P1-C3 — answerer's signed AAD. Pass-through; gateway does NOT inspect. */
    auth?:    CallControlAuthBlock;
  };
}

export interface ClientCallIce {
  event: 'call.ice';
  data: {
    callId:   CallId;
    to:       SessionAddress;
    /** ICE candidate payload — pass-through serialization of RTCIceCandidate. */
    candidate: string;
    sdpMid?:    string | null;
    sdpMLineIndex?: number | null;
  };
}

export interface ClientCallHangup {
  event: 'call.hangup';
  data: {
    callId:  CallId;
    to:      SessionAddress;
    /** busy | declined | ended | failed */
    reason:  'busy' | 'declined' | 'ended' | 'failed';
  };
}

/**
 * BS-021 — peer-mute / peer-camera-off advisory. Server forwards
 * verbatim like the rest of the call.* frames; never persisted.
 * On the receive side it lets the peer's UI show a "Camera off"
 * placeholder instead of a frozen last-frame image.
 */
export interface ClientCallMediaState {
  event: 'call.media-state';
  data: {
    callId:    CallId;
    to:        SessionAddress;
    cameraOff: boolean;
    micOff:    boolean;
    /** Audit P1-C2 — sender's signed AAD. Pass-through; gateway does NOT inspect. */
    auth?:     CallControlAuthBlock;
  };
}

/**
 * Mid-call SDP renegotiation — voice→video upgrade (and any future
 * mid-call media topology change). Distinct from `call.offer` so the
 * recipient can route it to the EXISTING controller via callId match
 * instead of treating it as an incoming call (which would mount a
 * fresh CallScreen and tear down the live one).
 *
 *   reoffer  — initiator (the side adding a video track) calls
 *              pc.setLocalDescription(createOffer()), ships the SDP.
 *   reanswer — responder applies the remote offer, optionally adds
 *              its own video, calls pc.createAnswer(), ships the SDP.
 *
 * Pure relay like the rest of the call.* family. Never queued offline
 * (peer is mid-call → already connected). On a peer running a client
 * that doesn't understand the frame, the dispatcher's switch falls
 * through with a no-op — initiator's local watchdog times out and
 * rolls back the half-applied upgrade.
 */
export interface ClientCallReOffer {
  event: 'call.reoffer';
  data: {
    callId: CallId;
    to:     SessionAddress;
    sdp:    string;
  };
}

export interface ClientCallReAnswer {
  event: 'call.reanswer';
  data: {
    callId: CallId;
    to:     SessionAddress;
    sdp:    string;
  };
}

// ─── Ephemeral signals (M11) — never persisted ───────────────────────
//
// Presence / typing / read-receipts are IN-MEMORY ONLY on the server.
// No Redis write, no envelope, no dwell. If the gateway process dies,
// these states reset cleanly — recipients learn the new state on the
// next heartbeat / typing event.

export interface ClientTyping {
  event: 'typing';
  data: {
    to:       SessionAddress;
    state:    'start' | 'stop';
    // Why: SYNC-6 — opaque 16-hex per-{sender,recipient} scope token, forwarded
    // verbatim; never the conversation id (group-clustering signal, FORBIDDEN).
    convTag?: string;
  };
}

export interface ClientReadReceipt {
  event: 'read-receipt';
  data: {
    to:          SessionAddress;
    /** The envelopeIds being acknowledged as read — batched. */
    envelopeIds: string[];
  };
}

/**
 * Presence heartbeat — clients send this periodically (e.g. every
 * 2 minutes) so the gateway can track active/away state. On connect the
 * gateway flips the user to `online` automatically; on the last socket's
 * disconnect it flips them to `offline`. Foreground/background
 * transitions send this event to refine the state to `active` / `away`.
 */
export interface ClientPresence {
  event: 'presence';
  data: {
    state: 'active' | 'away';
  };
}

/**
 * Subscribe to other users' live presence. The gateway joins this
 * socket to `watch:<userId>` rooms for every id in the payload and
 * emits a one-shot `presence` snapshot for each so the client can
 * populate its contact-status UI immediately.
 *
 * Subscriptions persist for the lifetime of the socket — clients should
 * resubscribe on reconnect unless connection state recovery kicks in.
 */
export interface ClientPresenceSubscribe {
  event: 'presence.subscribe';
  data:  {userIds: string[]};
}

export interface ClientPresenceUnsubscribe {
  event: 'presence.unsubscribe';
  data:  {userIds: string[]};
}

/**
 * Audit fix 5.1 — mission lifecycle subscription. Clients call this
 * when entering a live-mission screen so they get push frames
 * (status, team, telemetry) instead of polling. Unsubscribe on
 * navigate-away; a hard disconnect also drops the room membership.
 */
export interface ClientMissionSubscribe {
  event: 'mission.subscribe';
  data:  {missionId: string};
}

export interface ClientMissionUnsubscribe {
  event: 'mission.unsubscribe';
  data:  {missionId: string};
}

export type ClientFrame =
  | ClientPing
  | ClientAuthRefresh
  | ClientEnvelopeSend
  | ClientEnvelopeAck
  | ClientEnvelopePull
  | ClientCallOffer
  | ClientCallAnswer
  | ClientCallIce
  | ClientCallHangup
  | ClientCallMediaState
  | ClientCallReOffer
  | ClientCallReAnswer
  | ClientTyping
  | ClientReadReceipt
  | ClientPresence
  | ClientPresenceSubscribe
  | ClientPresenceUnsubscribe
  | ClientMissionSubscribe
  | ClientMissionUnsubscribe;

// ─── Server → Client ─────────────────────────────────────────────────

export interface ServerPong {
  event: 'pong';
  data: {ts: number};
}

export interface ServerEnvelopeAccepted {
  event: 'envelope.accepted';
  data: {
    clientMsgId:   string;
    envelopeId:    string;
    /** Capability token for sender-initiated retract — see envelope.service.ts. */
    retractToken?: string;
  };
}

export interface ServerEnvelopeDeliver {
  event: 'envelope.deliver';
  data: {
    envelopeId: string;
    /** Sealed Sender v2 outer ECIES wrap — see ClientEnvelopeSend.outerSealed. */
    outerSealed: string;
    timestamp:  number;
    /**
     * Audit P0-N9 — possession-proof token. Random per-envelope value
     * minted by the relay on first delivery and stored under
     * `ack_token:{envelopeId}` with the same TTL as the envelope.
     * The recipient MUST present this token back on `envelope.ack`
     * (and on POST /envelopes/:id/ack). Optional on the wire during
     * the rollout window so legacy clients are not broken; the
     * service enforces strictly once `relay.requireAckToken=true`.
     */
    ackToken?: string;
  };
}

/**
 * Audit P0-T6 — recipient acked, sender can paint the double-tick.
 * Emitted to the original submitter device when the recipient hits
 * `envelope.ack`. See the messenger-core mirror for the full rationale
 * (sealed-sender preservation, scope, etc).
 */
export interface ServerEnvelopeDelivered {
  event: 'envelope.delivered';
  data: {
    envelopeId: string;
  };
}

/**
 * Handoff §3.6(c) — honest counterpart of `envelope.delivered`: the
 * recipient acked with `disposition: 'discarded'` (terminal decrypt
 * failure — the message will never render on their device). Sender
 * paints `undelivered` instead of a lying ✓✓. Same submitter-mapping
 * privacy posture as `envelope.delivered`.
 */
export interface ServerEnvelopeUndeliverable {
  event: 'envelope.undeliverable';
  data: {
    envelopeId: string;
  };
}

export interface ServerError {
  event: 'error';
  data: {code: string; message: string};
}

// Server mirrors of the call.* frames — each carries a `from` address
// so the callee can route answers / ICE back.

export interface ServerCallOffer {
  event: 'call.offer';
  data: {
    callId: CallId; from: SessionAddress; sdp: string; kind: 'voice' | 'video';
    /** Audit S7 — forwarded verbatim from the caller; relay does not inspect. */
    auth?: CallOfferAuthBlock;
  };
}
export interface ServerCallAnswer {
  event: 'call.answer';
  data: {
    callId: CallId; from: SessionAddress; sdp: string;
    /** Audit P1-C3 — forwarded verbatim from the answerer; relay does not inspect. */
    auth?:  CallControlAuthBlock;
  };
}
export interface ServerCallIce {
  event: 'call.ice';
  data: {
    callId: CallId; from: SessionAddress; candidate: string;
    sdpMid?: string | null; sdpMLineIndex?: number | null;
  };
}
export interface ServerCallHangup {
  event: 'call.hangup';
  data: {callId: CallId; from: SessionAddress; reason: 'busy'|'declined'|'ended'|'failed'};
}

/**
 * BS-021 — server-side mirror of the client media-state advisory.
 * `from` is the peer who toggled their track.
 */
export interface ServerCallMediaState {
  event: 'call.media-state';
  data: {
    callId:    CallId;
    from:      SessionAddress;
    cameraOff: boolean;
    micOff:    boolean;
    /** Audit P1-C2 — forwarded verbatim from the sender; relay does not inspect. */
    auth?:     CallControlAuthBlock;
  };
}

/**
 * Server mirrors of the renegotiation frames — `from` is the peer who
 * is initiating (reoffer) or replying to (reanswer) the renegotiation.
 */
export interface ServerCallReOffer {
  event: 'call.reoffer';
  data: {callId: CallId; from: SessionAddress; sdp: string};
}

export interface ServerCallReAnswer {
  event: 'call.reanswer';
  data: {callId: CallId; from: SessionAddress; sdp: string};
}

/**
 * SYNC-6 — `convTag` is an OPAQUE 16-hex scope token bound to the
 * {sender, recipient} pair (client-computed). It is never the group id:
 * two members of the same group receive different tags, so the relay
 * cannot cluster it into a membership set. Never stored, never logged,
 * never in Redis. Absent = legacy peer (client falls back to fan-out).
 */
export interface ServerTyping {
  event: 'typing';
  data: {from: SessionAddress; state: 'start' | 'stop'; convTag?: string};
}

export interface ServerReadReceipt {
  event: 'read-receipt';
  data: {from: SessionAddress; envelopeIds: string[]};
}

export interface ServerPresence {
  event: 'presence';
  data: {
    userId: string;
    /**
     * `online` — connected, no active/away hint yet
     * `active` — foreground + interacting
     * `away`   — backgrounded / idle
     * `offline` — no sockets for this user anywhere in the cluster
     */
    state:  'online' | 'active' | 'away' | 'offline';
    /** epoch ms of the last state transition. */
    lastSeenMs?: number;
  };
}

/**
 * Audit fix 5.1 — mission lifecycle frames pushed to subscribed clients.
 * `mission.status` carries the new FSM state; `mission.team` is a
 * cache-invalidation nudge (the client re-fetches `/bookings/:id/team`
 * via REST so we don't have to re-implement region scoping on the WS);
 * `mission.telemetry` carries the latest GPS fix.
 */
export interface ServerMissionStatus {
  event: 'mission.status';
  data: {
    missionId: string;
    status?:   string;
    /** Set when an SOS event is acknowledged — surfaces ack in real-time. */
    sosAcked?: boolean;
    ackedBy?:  string;
    ts:        number;
  };
}

export interface ServerMissionTeam {
  event: 'mission.team';
  data: {missionId: string; ts: number};
}

export interface ServerMissionTelemetry {
  event: 'mission.telemetry';
  data: {
    missionId:  string;
    lat:        number;
    lng:        number;
    recordedAt: string;
    ts:         number;
  };
}

export interface ServerMissionSubscribed {
  event: 'mission.subscribed';
  data:  {missionId: string};
}

export interface ServerMissionUnsubscribed {
  event: 'mission.unsubscribed';
  data:  {missionId: string};
}

export type ServerFrame =
  | ServerPong
  | ServerEnvelopeAccepted
  | ServerEnvelopeDeliver
  | ServerEnvelopeDelivered
  | ServerEnvelopeUndeliverable
  | ServerError
  | ServerCallOffer
  | ServerCallAnswer
  | ServerCallIce
  | ServerCallHangup
  | ServerCallMediaState
  | ServerCallReOffer
  | ServerCallReAnswer
  | ServerTyping
  | ServerReadReceipt
  | ServerPresence
  | ServerMissionStatus
  | ServerMissionTeam
  | ServerMissionTelemetry
  | ServerMissionSubscribed
  | ServerMissionUnsubscribed;

export const WS_CLOSE_UNAUTHORIZED = 4401;
export const WS_CLOSE_POLICY       = 4403;
export const WS_CLOSE_HEARTBEAT    = 4408;
