/**
 * Expo config plugin — iOS build fixes that `expo prebuild` would otherwise
 * silently destroy (B-109 / docs/runbooks/IOS_README.md §5, docs/runbooks/IOS_BUILD.md).
 *
 * Re-applies, idempotently, on every prebuild:
 *   1. Podfile: export ENV['USE_FRAMEWORKS'] from Podfile.properties.json.
 *      RN's install_modules_dependencies only adds the React_*.framework
 *      header search paths when the env var is set — the Expo build
 *      property alone is not enough; without this the build fails with
 *      `react/utils/FollyConvert.h not found`.
 *   2. project.pbxproj: ENABLE_USER_SCRIPT_SANDBOXING = NO on every build
 *      configuration (Xcode 26 defaults YES → react-native-xcode.sh dies
 *      writing ip.txt into the bundle).
 *   3. project.pbxproj: quote the "Bundle React Native code and images"
 *      script invocation — the repo path contains a space ("Office Work")
 *      and the RN template's unquoted `/bin/sh -c "$WITH_ENVIRONMENT
 *      $REACT_NATIVE_XCODE"` re-splits on it.
 *
 * A missing anchor logs loudly instead of failing the prebuild, so template
 * drift surfaces in the prebuild output rather than as a mystery build break.
 */
const {withDangerousMod, withXcodeProject} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const USE_FRAMEWORKS_EXPORT = [
  '# @generated by withIosBuildFixes — RN install_modules_dependencies needs the env var',
  "ENV['USE_FRAMEWORKS'] = podfile_properties['ios.useFrameworks'] if podfile_properties['ios.useFrameworks']",
].join('\n');

function patchPodfile(config) {
  return withDangerousMod(config, [
    'ios',
    cfg => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      if (!fs.existsSync(podfile)) {
        console.warn('[withIosBuildFixes] ios/Podfile not found — skipping USE_FRAMEWORKS export');
        return cfg;
      }
      let src = fs.readFileSync(podfile, 'utf8');
      if (src.includes("ENV['USE_FRAMEWORKS']")) {
        return cfg;
      }
      const anchor = /^(podfile_properties\s*=\s*JSON\.parse[^\n]*)$/m;
      if (!anchor.test(src)) {
        console.warn(
          '[withIosBuildFixes] Podfile anchor (podfile_properties = JSON.parse…) not found — ' +
            'template drift? USE_FRAMEWORKS export NOT applied; the iOS build will fail under use_frameworks.',
        );
        return cfg;
      }
      src = src.replace(anchor, `$1\n${USE_FRAMEWORKS_EXPORT}`);
      fs.writeFileSync(podfile, src);
      return cfg;
    },
  ]);
}

// On-disk pbxproj escaping: `\"` is a quote inside the quoted shellScript,
// `\\\"` is a backslash-escaped quote handed through to /bin/sh.
const UNQUOTED_INVOKE = String.raw`/bin/sh -c \"$WITH_ENVIRONMENT $REACT_NATIVE_XCODE\"`;
const QUOTED_INVOKE = String.raw`/bin/sh -c \"\\\"$WITH_ENVIRONMENT\\\" \\\"$REACT_NATIVE_XCODE\\\"\"`;

// Expo SDK 54 does not emit the bare RN template's
// `$WITH_ENVIRONMENT $REACT_NATIVE_XCODE` form above. It emits a backtick
// command substitution that resolves the script path and then executes it
// UNQUOTED:
//   `"$NODE_BINARY" --print "...+ '/scripts/react-native-xcode.sh'"`
// The substitution expands to an absolute path; with a repo path containing
// a space ("Office Work") /bin/sh word-splits it and the phase dies with
// `/Users/sirajul/Desktop/Office: No such file or directory`. Wrapping the
// substitution in quotes makes the resolved path a single word.
const EXPO_INVOKE_RE = /`\\"\$NODE_BINARY\\"[^`]*?react-native-xcode\.sh'\\"`/;
const EXPO_INVOKE_QUOTED_RE = /\\"`\\"\$NODE_BINARY\\"[^`]*?react-native-xcode\.sh'\\"`\\"/;

function patchXcodeProject(config) {
  return withXcodeProject(config, cfg => {
    const project = cfg.modResults;

    const configurations = project.pbxXCBuildConfigurationSection();
    for (const key of Object.keys(configurations)) {
      const entry = configurations[key];
      if (entry && typeof entry === 'object' && entry.buildSettings) {
        entry.buildSettings.ENABLE_USER_SCRIPT_SANDBOXING = 'NO';
      }
    }

    const phases =
      project.hash && project.hash.project && project.hash.project.objects
        ? project.hash.project.objects.PBXShellScriptBuildPhase
        : null;
    let bundlePhaseSeen = false;
    if (phases) {
      for (const key of Object.keys(phases)) {
        const phase = phases[key];
        if (!phase || typeof phase !== 'object' || typeof phase.shellScript !== 'string') {
          continue;
        }
        if (!String(phase.name ?? '').includes('Bundle React Native')) {
          continue;
        }
        bundlePhaseSeen = true;
        if (phase.shellScript.includes(UNQUOTED_INVOKE)) {
          phase.shellScript = phase.shellScript.replace(UNQUOTED_INVOKE, QUOTED_INVOKE);
        } else if (EXPO_INVOKE_QUOTED_RE.test(phase.shellScript)) {
          // Already quoted by a previous run — idempotent no-op.
        } else if (EXPO_INVOKE_RE.test(phase.shellScript)) {
          phase.shellScript = phase.shellScript.replace(EXPO_INVOKE_RE, m => `\\"${m}\\"`);
        } else if (!phase.shellScript.includes(QUOTED_INVOKE)) {
          console.warn(
            '[withIosBuildFixes] "Bundle React Native code and images" phase has an unexpected ' +
              'shellScript shape — quoting fix NOT applied; a repo path with spaces will break the bundle phase.',
          );
        }
      }
    }
    if (!bundlePhaseSeen) {
      console.warn(
        '[withIosBuildFixes] no "Bundle React Native" script phase found — quoting fix skipped',
      );
    }
    return cfg;
  });
}

module.exports = function withIosBuildFixes(config) {
  return patchXcodeProject(patchPodfile(config));
};
