/**
 * Expo config plugin — iOS PushKit (VoIP) + CallKit native wiring.
 *
 * ios/ is gitignored and regenerated by `expo prebuild`, which would wipe the
 * hand-added AppDelegate PushKit code and the bridging-header imports. This
 * plugin re-applies both on every prebuild. Idempotent: each injection is
 * guarded so re-running (or a partially-modified file) is safe.
 *
 * aps-environment and UIBackgroundModes:voip are handled by app.json
 * (ios.entitlements / ios.infoPlist), not here.
 *
 * After any prebuild, verify against docs/runbooks/IOS_CALLKIT_VOIP.md §6.
 */
const {withDangerousMod, withAppDelegate} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const BRIDGING_IMPORTS = [
  '#import <RNVoipPushNotification/RNVoipPushNotificationManager.h>',
  '#import <RNCallKeep/RNCallKeep.h>',
];

const VOIP_REGISTRATION = '    RNVoipPushNotificationManager.voipRegistration()';

/**
 * First statement of didFinishLaunchingWithOptions in the Expo SDK 54
 * ExpoAppDelegate template. Used as the injection anchor because it is
 * present in every generated AppDelegate, unlike FirebaseApp.configure()
 * (see the note on the Firebase block below).
 */
const RN_DELEGATE_ANCHOR = /(\n?[ \t]*let delegate = ReactNativeDelegate\(\))/;

const FIREBASE_CONFIGURE = `
    // Why: RNFB requires the default FIRApp before any JS firebase call
    // (index.js registers the FCM background handler at bundle entry).
    // Guarded so a build without GoogleService-Info.plist still boots.
    if FirebaseApp.app() == nil,
       Bundle.main.path(forResource: "GoogleService-Info", ofType: "plist") != nil {
      FirebaseApp.configure()
    }
`;

const PUSHKIT_METHODS = `
  // MARK: - PushKit (VoIP) — PKPushRegistryDelegate (added by withVoipCallKit)
  public func pushRegistry(
    _ registry: PKPushRegistry,
    didUpdate pushCredentials: PKPushCredentials,
    for type: PKPushType
  ) {
    RNVoipPushNotificationManager.didUpdate(pushCredentials, forType: type.rawValue)
  }

  public func pushRegistry(
    _ registry: PKPushRegistry,
    didReceiveIncomingPushWith payload: PKPushPayload,
    for type: PKPushType,
    completion: @escaping () -> Void
  ) {
    let dict = payload.dictionaryPayload
    // CallKit's CXProvider REQUIRES a valid UUID — a non-UUID callId makes
    // reportNewIncomingCall throw and crash the app inside the 5s window
    // (VoIP entitlement revocation). Normalise: use callId only if it parses.
    let uuid = (dict["callId"] as? String).flatMap { UUID(uuidString: $0)?.uuidString } ?? UUID().uuidString
    let callerName = (dict["callerName"] as? String) ?? "Bravo contact"
    // B-112 — callKind now rides the wake (group-video counts as video).
    let kindStr = (dict["callKind"] as? String) ?? ""
    let hasVideo = kindStr == "video" || kindStr == "group-video"
    RNVoipPushNotificationManager.didReceiveIncomingPush(with: payload, forType: type.rawValue)
    // B-113 — the host cancelled: end the CXCall that the earlier ring push
    // reported under this SAME uuid. The 5s contract still requires a
    // report per VoIP push, so report first (a duplicate uuid is a no-op
    // flash at worst) and immediately end — the ring stops either way.
    if (dict["kind"] as? String) == "call-cancel" {
      RNCallKeep.reportNewIncomingCall(
        uuid, handle: callerName, handleType: "generic", hasVideo: false,
        localizedCallerName: callerName, supportsHolding: false, supportsDTMF: false,
        supportsGrouping: false, supportsUngrouping: false, fromPushKit: true,
        payload: dict, withCompletionHandler: {})
      RNCallKeep.endCall(withUUID: uuid, reason: 2)
      completion()
      return
    }
    RNCallKeep.reportNewIncomingCall(
      uuid, handle: callerName, handleType: "generic", hasVideo: hasVideo,
      localizedCallerName: callerName, supportsHolding: true, supportsDTMF: false,
      supportsGrouping: false, supportsUngrouping: false, fromPushKit: true,
      payload: dict, withCompletionHandler: completion)
  }
`;

function patchBridgingHeader(config) {
  return withDangerousMod(config, [
    'ios',
    cfg => {
      const root = cfg.modRequest.platformProjectRoot;
      const candidates = fs
        .readdirSync(root, {withFileTypes: true})
        .filter(d => d.isDirectory())
        .map(d => path.join(root, d.name, `${d.name}-Bridging-Header.h`))
        .filter(p => fs.existsSync(p));
      for (const file of candidates) {
        let src = fs.readFileSync(file, 'utf8');
        for (const imp of BRIDGING_IMPORTS) {
          if (!src.includes(imp)) {
            src += `\n${imp}\n`;
          }
        }
        fs.writeFileSync(file, src);
      }
      return cfg;
    },
  ]);
}

function patchAppDelegate(config) {
  return withAppDelegate(config, cfg => {
    let src = cfg.modResults.contents;
    // Swift AppDelegate only (Expo SDK 54+).
    if (!src.includes('ExpoAppDelegate')) {
      return cfg;
    }

    if (!src.includes('import PushKit')) {
      src = src.replace(/import Expo\n/, 'import Expo\nimport PushKit\n');
    }
    if (!src.includes('PKPushRegistryDelegate')) {
      src = src.replace(
        /(class AppDelegate: ExpoAppDelegate)(\s*\{)/,
        '$1, PKPushRegistryDelegate$2',
      );
    }
    if (!src.includes('import FirebaseCore')) {
      src = src.replace(/import Expo\n/, 'import Expo\nimport FirebaseCore\n');
    }
    // Why: @react-native-firebase/app's plugin can no longer locate its
    // insertion point in the SDK 54 ExpoAppDelegate template — prebuild logs
    // "Unable to determine correct Firebase insertion point in
    // AppDelegate.swift. Skipping Firebase addition." — so FirebaseApp
    // .configure() never lands and Firebase silently never initialises.
    // Inject it here, ahead of voipRegistration, preserving the order the
    // hand-built AppDelegate used.
    if (!src.includes('FirebaseApp.configure()')) {
      src = src.replace(RN_DELEGATE_ANCHOR, `${FIREBASE_CONFIGURE}$1`);
    }
    // Why: this was previously anchored on the FirebaseApp.configure() guard
    // block. Once RNFB stopped injecting that, the regex matched nothing and
    // voipRegistration was silently dropped — the PushKit delegate methods
    // still compiled, so the code read as wired while the app never
    // registered for VoIP pushes (no token, no CallKit ring). Anchor on the
    // template's own first statement instead, which always exists.
    if (!src.includes('RNVoipPushNotificationManager.voipRegistration()')) {
      src = src.replace(RN_DELEGATE_ANCHOR, `\n${VOIP_REGISTRATION}\n$1`);
    }
    if (!src.includes('didReceiveIncomingPushWith payload')) {
      // Inject before the final closing brace of the AppDelegate class —
      // anchored on the ReactNativeDelegate class that follows it.
      src = src.replace(
        /\n\}\n\nclass ReactNativeDelegate/,
        `\n${PUSHKIT_METHODS}}\n\nclass ReactNativeDelegate`,
      );
    }
    cfg.modResults.contents = src;
    return cfg;
  });
}

module.exports = function withVoipCallKit(config) {
  return patchAppDelegate(patchBridgingHeader(config));
};
