/**
 * IndexedDB schema for the web messenger crypto store. Mirrors the
 * mobile SQLCipher schema row-for-row so libsignal sessions ratchet
 * identically across platforms.
 *
 * Every value column is encrypted at rest with the AES-GCM key derived
 * from the admin's vault passphrase (see crypto.ts). Primary keys live
 * in plaintext so we can index/look up without unwrapping every row.
 */

import {openDB, type IDBPDatabase} from 'idb';

export interface MessengerSchema {
  /** Single-row table (key=1) holding the wrapped local identity. */
  identity: {
    key: 1;
    value: {
      registration_id: Uint8Array;   // wrapped number
      public_key:      Uint8Array;   // wrapped buffer
      private_key:     Uint8Array;   // wrapped buffer
      created_at:      number;
    };
  };
  pre_keys: {
    key: number;
    value: {
      key_id:      number;
      public_key:  Uint8Array;
      private_key: Uint8Array;
    };
  };
  signed_pre_keys: {
    key: number;
    value: {
      key_id:      number;
      public_key:  Uint8Array;
      private_key: Uint8Array;
      signature:   Uint8Array;
      created_at:  number;
    };
  };
  sessions: {
    key: string;                     // address
    value: {
      address:    string;
      record:     Uint8Array;        // wrapped utf-8 (libsignal serialized)
      updated_at: number;
    };
  };
  trusted_identities: {
    key: string;                     // address
    value: {
      address:      string;
      identity_key: Uint8Array;      // wrapped buffer
      first_seen:   number;
      /**
       * Audit P0-W7 — verification fingerprint (sha256 hex over the
       * displayed safety number) recorded when the operator clicked
       * "Verify" on this peer. Null until verified. `verified_at_ms`
       * is the wall-clock at confirmation. Both clear on rotation so
       * a re-verify is required.
       */
      verified_at_ms?:          number | null;
      verified_safety_number?:  string | null;
    };
  };
  /**
   * Audit P0-W7 — append-only forensic trail of identity rotations.
   * Every observed peer-identity change writes one row; UI surfaces
   * it as a "safety number changed" banner with the rotation history
   * so an operator can see whether the peer reinstalled recently or
   * something more suspicious happened.
   */
  identity_rotations: {
    key: number;                     // auto-incrementing rotation id
    value: {
      rotation_id:    number;
      address:        string;
      prev_key:       Uint8Array;    // wrapped buffer (previous identity)
      new_key:        Uint8Array;    // wrapped buffer (incoming identity)
      detected_at_ms: number;
    };
  };
  /** Tracks the highest envelope timestamp we've already pulled. */
  meta: {
    key: string;
    value: {key: string; value: string};
  };
  /**
   * Singleton holding the salt + canary blob the unlock flow uses to
   * verify the passphrase. Plaintext salt + AES-GCM canary so wrong
   * passphrases fail cleanly via the GCM tag.
   */
  vault: {
    key: 1;
    value: {
      salt:      Uint8Array;
      canary:    Uint8Array;         // wrapped string 'OK' (passphrase-derived key)
      created_at: number;
      // Audit fix 4.7 — optional passkey enrollment for the vault.
      // When present, an alternate canary is unwrappable with the
      // PRF-derived key from a WebAuthn authenticator. The passphrase
      // path stays intact; passkey is additive so an operator with a
      // wiped authenticator can recover via password.
      passkey_credential_id?: Uint8Array;
      passkey_prf_salt?:      Uint8Array;
      passkey_canary?:        Uint8Array;  // wrapped string 'OK' (PRF-derived key)
    };
  };
  /**
   * Per-group AES-256-GCM master key. Distributed in-band via admin
   * `create` envelopes, so the value here was either generated by
   * this device (we're the group creator) or learned from a trusted
   * peer over a verified pairwise Signal session.
   *
   * Audit OPS-MSG-02 — the key is wrapped with the vault AES-GCM key
   * (`master_key_wrapped`), matching every other secret in this store,
   * so an IDB exfil (XSS / disk forensics) yields ciphertext only.
   * `master_key_b64` is the legacy plaintext column kept for read-time
   * migration of rows written before this fix; setGroupKey never writes
   * it again.
   */
  group_keys: {
    key: string;                     // groupId
    value: {
      group_id:            string;
      master_key_wrapped?: Uint8Array; // wrapped base64 string (vault AES-GCM)
      master_key_b64?:     string;     // legacy plaintext (pre-OPS-MSG-02)
      epoch:               number;
      updated_at:          number;
    };
  };
  /**
   * Conversation history mirror — every inbound + outbound message body
   * is wrapped with the vault key and stored here so the dock can hydrate
   * its thread on reload. Mirrors the SQLCipher `messages` table mobile
   * already maintains (`src/modules/messenger/crypto/db.ts`). Primary
   * key is `"<conversationId>|<messageId>"` so range queries on a
   * conversation key prefix are O(log n).
   */
  messages: {
    key: string;                     // `${conversation_id}|${id}`
    value: {
      pk:              string;       // matches the IDB key — explicit so range queries are scrutable
      conversation_id: string;
      id:              string;
      sender_user_id:  string;
      direction:       'in' | 'out';
      body:            Uint8Array;   // wrapped utf-8
      sent_at:         number;
      envelope_id:     string | null;
      client_msg_id:   string | null;
      status:          'sending' | 'sent' | 'delivered' | 'read' | 'failed';
      reactions_json:  Uint8Array | null; // wrapped JSON {[userId]: emoji}
      reply_to_id:     string | null;
    };
  };
}

export type MessengerDb = IDBPDatabase<MessengerSchema>;

const REQUIRED_STORES = [
  'identity', 'pre_keys', 'signed_pre_keys',
  'sessions', 'trusted_identities', 'meta', 'vault', 'group_keys',
  'messages',
  // Audit P0-W7 — identity rotation forensic trail.
  'identity_rotations',
] as const;

function applySchema(db: IDBPDatabase<MessengerSchema>) {
  if (!db.objectStoreNames.contains('identity'))
    db.createObjectStore('identity');
  if (!db.objectStoreNames.contains('pre_keys'))
    db.createObjectStore('pre_keys',         {keyPath: 'key_id'});
  if (!db.objectStoreNames.contains('signed_pre_keys'))
    db.createObjectStore('signed_pre_keys',  {keyPath: 'key_id'});
  if (!db.objectStoreNames.contains('sessions'))
    db.createObjectStore('sessions',         {keyPath: 'address'});
  if (!db.objectStoreNames.contains('trusted_identities'))
    db.createObjectStore('trusted_identities', {keyPath: 'address'});
  if (!db.objectStoreNames.contains('meta'))
    db.createObjectStore('meta',             {keyPath: 'key'});
  if (!db.objectStoreNames.contains('vault'))
    db.createObjectStore('vault');
  if (!db.objectStoreNames.contains('group_keys'))
    db.createObjectStore('group_keys',       {keyPath: 'group_id'});
  if (!db.objectStoreNames.contains('messages')) {
    const store = db.createObjectStore('messages', {keyPath: 'pk'});
    // Range query on a single conversation: keyRange.bound('<cid>|', '<cid>|￿').
    // We also keep a sent_at index so loadConversation can return rows
    // already sorted without an in-memory pass on big histories.
    store.createIndex('by_conv_sent', ['conversation_id', 'sent_at']);
  }
  // Audit P0-W7 — identity rotation forensic trail. Auto-incrementing
  // PK so a peer that rotates twice keeps both events; secondary index
  // by address lets the ChatInfo UI surface "n rotations observed".
  if (!db.objectStoreNames.contains('identity_rotations')) {
    const store = db.createObjectStore('identity_rotations', {
      keyPath: 'rotation_id', autoIncrement: true,
    });
    store.createIndex('by_address_detected', ['address', 'detected_at_ms']);
  }
}

export async function openMessengerDb(userId: string): Promise<MessengerDb> {
  const name = `bravo-messenger-${userId}`;
  // Self-heal path: an earlier bug could create an empty v1 database
  // with NO object stores. Detect that and bump the version so the
  // upgrade callback fires and the schema is laid down.
  const probe = await openDB<MessengerSchema>(name, undefined, {});
  const missing = REQUIRED_STORES.filter(s => !probe.objectStoreNames.contains(s));
  const currentVersion = probe.version;
  probe.close();

  if (missing.length === 0) {
    return openDB<MessengerSchema>(name, currentVersion);
  }

  return openDB<MessengerSchema>(name, currentVersion + 1, {
    upgrade(db) { applySchema(db); },
  });
}

/** Wipe everything — used by the "reset identity" flow in the UI. */
export async function wipeMessengerDb(userId: string): Promise<void> {
  await indexedDB.deleteDatabase(`bravo-messenger-${userId}`);
}
