-- Audit fix Phase 1 — concurrency hardening migrations.
--
-- Bundles four schema-level guards:
--   1.2  Unique partial index on mission_crew(agent_id) — an agent can't
--        be active on two missions at once. Insert collisions surface as
--        a 23505 unique-violation, which the dispatch flow translates
--        into a "agent_already_assigned" 4xx.
--   1.7  Unique index on missions(short_code) — atomic generation gate.
--        Without this two ops admins running dispatchBooking() within
--        the same second can both INSERT a mission row with a colliding
--        short_code; the unique index forces one of them to retry.
--   2.2 (preview) FK on mission_crew.agent_id → agents(user_id).
--        The audit's Phase 2 includes this; landing it here piggybacks
--        on the integrity wave so the unique index isn't sitting on a
--        column that points at a soft reference.
--
-- Each statement is `IF NOT EXISTS` / `CREATE INDEX CONCURRENTLY`-safe-ish
-- so re-applying is a no-op.

-- 1.2 ─── unique active-membership per agent ────────────────────────────────
-- The audit asked for `WHERE status IN ('ASSIGNED','LIVE')`, but the actual
-- mission_crew schema uses 'active' / 'sos' / 'standby' / 'off'. The
-- rule is "an agent must not be on two non-off crews simultaneously" — so
-- we exclude 'off' (the soft delete) and keep everything else unique per
-- agent. SOS and standby are still "on this mission" from a scheduling
-- standpoint; assigning the same agent to a second mission while their
-- first is in SOS would be a dispatcher error, not a feature.
CREATE UNIQUE INDEX IF NOT EXISTS mission_crew_agent_active_uq
  ON mission_crew (agent_id)
  WHERE status <> 'off';

-- 1.7 ─── unique mission short-code ─────────────────────────────────────────
-- Mission short codes are user-facing identifiers ("MSN-A1B2C3D4E5F6").
-- Today they're generated from the booking id suffix, which is collision-
-- free for that flow — but historical rows used a sequential MSN-YYYY-NNNN
-- format generated by COUNT(*)+1, which races. Future job-feed dispatch
-- will fall back to short-code-from-id; the unique index guarantees both
-- paths remain unambiguous.
CREATE UNIQUE INDEX IF NOT EXISTS missions_short_code_uq
  ON missions (short_code);

-- The non-unique missions_short_idx (from 20260424000000_ops_admin.sql) is
-- now redundant since a unique index also serves as a lookup index. Drop
-- it to save the disk + the planner's index-choice work. IF EXISTS keeps
-- the migration idempotent if a future deploy reorders things.
DROP INDEX IF EXISTS missions_short_idx;
